import type { Metadata } from "next";
import { Poppins, Inter, DM_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const dmsans = DM_Sans({
  variable: "--font-dmsans",
  subsets: ["latin"],
});


const poppins = Poppins ({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Recipe Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${dmsans.variable} antialiased bg-light dark:bg-dark`}
      >
        {children}
      </body>
    </html>
  );
}
